name: Test and Deploy Nest App

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci

    - name: Build the Application
      run: npm run build

    - name: Run Tests
      run: npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP_HOST }}
          username: ${{ secrets.IP_USERNAME }}
          password: ${{ secrets.IP_PASS }}
          script: |
            # Pull the latest code from GitHub
            cd /home/workspace/ci-cd-fullstack-example/nest-app
            git pull origin master
            
            # Build the Docker image
            docker build -t nest-app:latest .

            # Run Docker container
            docker stop backend || true
            docker rm backend || true
            docker run -itd -p 8000:8000 --env-file .env --env-file .env.development  --name backend --network ci-cd-fullstack-example_nest_network nest-app:latest
